name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
jobs:
  project-build-test:
    uses: ./.github/workflows/npm-ci.yml
    with:
      skip-tests: true
